# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lyv' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lyv
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Kingfisher', '~> 4.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  

  target 'LyvTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LyvUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
